apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s
  namespace: argocd
spec:
  destination:
    namespace: system-upgrade
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/k3s/
    repoURL: https://github.com/Suguis/pintxo-renovate-infra
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

